source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!

def app
	pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'AlamofireImage'
  pod 'StatefulViewController'
  pod 'EasyPeasy'
  pod 'ObjectMapperAdditions'
  pod 'Hero'
  pod 'ObjectMapper'
  pod 'RealmSwift'
  pod 'ObjectMapper+Realm'
end

target 'Pokedex' do
  app
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end